# configs/backtest.yml：バックテスト専用の実行パラメタ
env: backtest                        # 【関数】BTモード指定

latency:                              # 【関数】遅延モデル（まずは固定ms）
  rx_ms: 30                           # 受信遅延：再生時の受信側待ち
  tx_ms: 30                           # 送信遅延：約定判定や発注側の遅れ

slippage:                             # 【関数】スリッページ係数（>=1.0で不利側補正）
  taker_multiplier: 1.2               # 成行/タッチ時にコストを悪化させる倍率

period:                                # 【関数】再生対象の期間（JSTのISO）
  start: "2025-08-25T00:00:00+09:00"  # 今日の0時（JST）
  end:   "2025-08-26T00:00:00+09:00"  # 明日の0時（JST）
